"""
    This module contains the database queries used in the application models
"""

CREATE_TABLE_USERS = """
    CREATE TABLE IF NOT EXISTS USERS (
    ID SERIAL PRIMARY KEY NOT NULL,
    FIRSTNAME VARCHAR(60) NOT NULL,
    LASTNAME VARCHAR(60) NOT NULL,
    OTHERNAME VARCHAR(50),
    USERNAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    ISADMIN BOOLEAN DEFAULT FALSE,
    PHONENUMBER INTEGER NOT NULL
    );
"""
CREATE_TABLE_MEETUPS = """
    CREATE TABLE IF NOT EXISTS MEETUPS (
    ID SERIAL PRIMARY KEY NOT NULL,
    TOPIC VARCHAR(112) NOT NULL,
    IMAGES VARCHAR(1024)[],
    LOCATION VARCHAR(50) NOT NULL,
    HAPPENING_ON DATE NOT NULL DEFAULT CURRENT_DATE,
    TAGS TEXT []
    );
"""

CREATE TABLE QUESTIONS = """
    CREATE TABLE IF NOT EXISTS QUESTIONS (
    );
"""
